### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by markknol** [twinspire/twinspire#1]
![image](https://cloud.githubusercontent.com/assets/576184/11178115/d48089b8-8c4a-11e5-9c4d-b74f12727e81.png)

Log:

```
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.34209
	System.Deployment.dll 		: 4.0.30319.34244 built by: FX452RTMGDR
	clr.dll 			: 4.0.30319.34209 built by: FX452RTMGDR
	dfdll.dll 			: 4.0.30319.34244 built by: FX452RTMGDR
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: file:///C:/xxxx/xxxx/xxxx/Twinspire.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\xxxx\xxxx\xxxx\Twinspire.application resulted in exception. Following failure messages were detected:
		+ Downloading file:///C:/xxxx/xxxx/xxxx/Twinspire.application did not succeed.
		+ Could not find file 'C:\xxxx\xxxx\xxxx\Twinspire.application'.
		+ Could not find file 'C:\xxxx\xxxx\xxxx\Twinspire.application'.
		+ Could not find file 'C:\xxxx\xxxx\xxxx\Twinspire.application'.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [16-11-2015 10:13:39] : Activation of C:\xxxx\xxxx\xxxx\Twinspire.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [16-11-2015 10:13:39] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file:///C:/xxxx/xxxx/xxxx/Twinspire.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'C:\xxxx\xxxx\xxxx\Twinspire.application'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			at System.Net.FileWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'C:\xxxx\xxxx\xxxx\Twinspire.application'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			at System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Inner Exception ---
		System.IO.FileNotFoundException
		- Could not find file 'C:\xxxx\xxxx\xxxx\Twinspire.application'.
		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
			at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

```

**Comment by tienery** [comment]
https://github.com/twinspire/twinspire/releases/tag/1.0.0.6

I've now updated the release section.
